---
- name: cleanup apt cache
  shell: rm -rf /var/lib/apt/lists/*; rm -rf /var/lib/apt/lists/partial/*
  
- name: apt upgrade
  apt: update_cache=yes force=yes

- name: add python package for adding new repository
  apt: name=python-software-properties state=present
  
- name: add new repository for php5.4
  apt_repository: repo=ppa:ondrej/php5-oldstable state=present
  when: web_php_version == "php5.4"
  
- name: install php5.4 packages
  apt: name={{item}} state=present
  with_items:
    - php5
    - php5-fpm
    - php5-mysql
    - php5-gd
    - php5-common
    - php5-mcrypt
    - php5-dev
    - php5-mysql
    - php5-curl
    
- name: option - memcache
  apt: name=php5-memcached state=present
  when: web_php_memcache == "true"
  
- name: option - imagemagick - linux package
  apt: name=imagemagick state=present
  when: web_php_imagemagick == "true"
  
- name: option - imagemagick - php package
  apt: name=php5-imagick state=present
  when: web_php_imagemagick == "true"
  
- name: check if ioncube script file exists
  stat: path=/root/ioncube.sh
  register: st
  
- name: option - ionCube - copy ioncube shell script to remote
  copy: src=ioncube.sh dest=/root/ owner=root group=root mode=0700
  when: st.stat.exists == false and web_php_ioncube == "true"
  
- name: option - ionCube - run ioncube shell script
  shell: cd /root/; ./ioncube.sh
  when: st.stat.exists == false and web_php_ioncube == "true"
  
- name: check if opcache script file exists
  stat: path=/root/opcache.sh
  register: sg
  
- name: install opcache dependency
  apt: name=build-essential state=present
  when: sg.stat.exists == false and web_php_opcache == "true"
  
- name: option - OpCache - copy zend opcache script to remote
  copy: src=opcache.sh dest=/root/ owner=root group=root mode=0700
  when: sg.stat.exists == false and web_php_opcache == "true"
  
- name: option - OpCache - run opcache shell script
  shell: cd /root/; ./opcache.sh {{web_php_opcache_memory_consumption}} {{web_php_opcache_interned_strings_buffer}} {{web_php_opcache_enable_cli}} {{web_php_opcache_revalidate_freq}} {{web_php_opcache_max_accelerated_files}} {{web_php_opcache_version}}
  when: sg.stat.exists == false and web_php_opcache == "true"
  
- name:  update php.ini for fpm
  template: src=php-fpm.ini dest=/etc/php5/fpm/php.ini owner=root group=root mode=0644
  
- name: update php.ini for cli
  template: src=php-cli.ini dest=/etc/php5/cli/php.ini owner=root group=root mode=0644
  
- name: create web group
  group: name={{web_group}} state=present

- name: create web user
  user: name={{web_user}} group={{web_group}} createhome="yes" state=present shell=/bin/bash
  
- name: create log directory
  file: path=/home/{{web_user}}/log group={{web_group}} owner={{web_user}} state=directory
  
- name: update php5-fpm.conf
  template: src=php-fpm.conf dest=/etc/php5/fpm/php-fpm.conf owner=root group=root mode=0644
  
- name: copy php logrotate script
  template: src=php-logrotate.d.ini dest=/etc/logrotate.d/php5-fpm
  
- name: update www.conf for fpm
  template: src=php-fpm-www.conf dest=/etc/php5/fpm/pool.d/www.conf owner=root group=root mode=0644
  notify: restart php5-fpm
  
- name: ensure php-fpm start on boot
  service: name=php5-fpm enabled=yes

  